# Site settings
title: 'Kevin'  # Your Title
tagline: 'æŸ”å¼±ã€æ— æ¬²ï¼Œé¡ºä¹è‡ªç„¶ï¼Œä½†å´å…·æœ‰å¼ºå¤§çš„ç”Ÿå‘½åŠ?  # A brief tagline for your site
sidebar_image: /images/cover.jpg

encoding: UTF-8
markdown: kramdown

paginate: 8
paginate_path: "page:num"

#pygments: true
baseurl: ""


# Site settings
name:           kevin
email:          958987180@qq.com
uri:            TouchmyDream.github.io
github:         TouchmyDream
twitter:        TouchmyDream
facebook:       TouchmyDream
linkedin:       TouchmyDream